// <auto-generated />
namespace SATS.VeriTabani.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DateTimeSorunu2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DateTimeSorunu2));
        
        string IMigrationMetadata.Id
        {
            get { return "201803241858576_DateTimeSorunu2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
